### ISSUE TITLE
Test for funcfiletrace used in configure is broken on zsh 5.3

### ISSUE THREAD

**Issue by irl** [rocky/zshdb#9]
https://bugs.debian.org/851501

Instead of parsing the output of ``declare -p``, instead use ``if (( ${+funcfiletrace} ))`` as this is no longer listed in that output.

An explicit ``zmodload zsh/parameter`` also could not hurt.

**Comment by rocky** [comment]
I guess you are referring to https://github.com/rocky/zshdb/blob/master/test/zsh/ok4zshdb.sh#L7 ? 

Since you are there in the weeds already would you please make a patch and suggest that. I just looked and I'm currrently using zsh 5.1.1 (x86_64-ubuntu-linux-gnu). 

Likewise with the suggestion to use `zmodload zsh/parameter`. 

Thanks.
